"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import glob
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure--7c7pud34&b=hw&!ef-0y=scn&n1=$jyx+38cf3hd&ixu_a8bc'

DEBUG = True

ALLOWED_HOSTS = ['*']

if os.name == 'nt':
    OSGEO4W = r"C:\\Users\\kissu\AppData\\Local\\Programs\\OSGeo4W"
    OSGEO4W_BIN = os.path.join(OSGEO4W,"bin")

    os.environ['PATH'] = os.path.join(OSGEO4W,"bin")+ ";" + os.environ['PATH'] 
    try:
        os.add_dll_directory(OSGEO4W_BIN)
    except (AttributeError, OSError):
        pass

    gdal_dlls = glob.glob(os.path.join(OSGEO4W_BIN, "gdal*.dll"))

    if gdal_dlls:
        GDAL_LIBRARY_PATH = gdal_dlls[-1]
        GEOS_LIBRARY_PATH = os.path.join(OSGEO4W_BIN, "geos_c.dll")
    else:
        print(f"WARNING: No gdal*.dll found in {OSGEO4W_BIN}. GeoDjango may fail.")

    if os.path.exists(os.path.join(OSGEO4W, "share", "gdal")):
        os.environ['GDAL_DATA'] = os.path.join(OSGEO4W, "share", "gdal")
    else:
        os.environ['GDAL_DATA'] = os.path.join(OSGEO4W, "apps", "gdal", "share", "gdal")

    os.environ['PROJ_LIB'] = os.path.join(OSGEO4W,"share","proj")        


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django.contrib.gis', 
    'fuel_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'spotter_django',
        'USER': 'postgres',
        'PASSWORD': 'Kgf@2018',
        'HOST': 'localhost',
        'PORT': '5432',

    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ORS_API_KEY = 'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjdhOGYwMmMyN2U3NzRkYzA5MzBiYmY0ZTQwOWU4ZTQ2IiwiaCI6Im11cm11cjY0In0='